config/routes.rb
Sss::Application.routes.draw do
  resources :users

  match 'invite_user/:id' => 'users#invite_user', :as => :invite_user
  match 'invite_users' => 'users#invite_users'
  match 'remind_users' => 'users#remind_users'
  match 'rsvp' => 'users#rsvp'
  match 'confirm_rsvp' => 'users#confirm_rsvp'
  match 'match' => 'users#match'
  match 'send_matches' => 'users#send_matches'

  root :to => 'users#rsvp'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :user_id, :rsvp

  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def invite_user
    EmailMatches.invite_email(User.find(params[:id])).deliver
    redirect_to users_path
  end

  def invite_users
    User.all.each do |user|
      EmailMatches.invite_email(user).deliver
    end
    redirect_to users_path
  end

  def remind_users
    User.where(rsvp: false).each do |user|
      EmailMatches.remind_email(user).deliver
    end
    redirect_to users_path
  end

  def rsvp
    # just a route to pair with a view
  end

  def confirm_rsvp
    @user = User.find_by_email(params[:email])

    if !@user.nil?
      @user.update_attribute(:rsvp, true)
      EmailMatches.accepted_invite(@user).deliver
    end

    respond_to do |format|
      format.js
    end
  end

  def match
    ids = User.where(rsvp: true).collect{|u| u.id}
    User.all.each do |user|
      user.update_attribute(:user, nil)
    end
    User.where(rsvp: true).each do |user|
      user.user = nil
      ids = ids - [user.id]
      user_id = ids.sample
      logger.debug user_id
      user.user = User.find(user_id)
      ids = ids - [user_id]
      user.save
      if User.where(user_id: user.id).count == 0
        ids << user.id
      end
    end
    redirect_to users_path
  end

  def send_matches
    User.where(rsvp: true).each do |user|
      EmailMatches.send_matches(user).deliver
    end
    redirect_to users_path
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/email_matches/accepted_invite.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @user.first_name %></h1>
    <p>
      Congratulations. You're officially a member of the S3. We knew you'd make the right choice.</p>
    <p>We don't have much information that we can share right now, but we can tell you that our annual secret meeting this year will take place at an undisclosed location, at 7PM on Saturday, December 15th.</p>
    <p>On Friday, December 7th at midnight, you will receive a secret santa match name, as well as the location of the party. Once you receive your match name, you can begin finding and purchasing the perfect gift for them.</p>
    <p>That's all the information I have for you until the 7th at midnight. Until then, remember: we DO NOT talk about Secret Santa Society.

    <p>— Josh Ferrara &amp; the S3</p>

  </body>
</html>

app/views/email_matches/invite_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @user.first_name %></h1>
    <p>Congratulations. You've been chosen to be part of what most holiday analysts are saying is the biggest thing to happen to Christmas since egg nog and mistletoe. </p>

    <p>Obviously, I'm talking about the annual meeting of the Secret Santa Society, the SSS, or as we like to call it, S3. You've probably never heard of it. That's sort of the point. </p>

    <p>Here's how it works:</p>

    <ol>
      <li>If you choose to participate, visit <a href="<%= @url %>"><%= @url %></a> by end of day Friday, December 7th to accept this invitation.</li>
      <li>At midnight on Friday, December 7th you will receive an email with a Secret Santa match name. This is the person you will be buying a gift for.</li>
      <li>On Saturday, December 15th the S3 will convene (that means get together for a Christmas party) for our annual gathering at an undisclosed location, and gifts will be exchanged anonymously.</li>
    </ol>

    <p>That's it. </p>

    <p>We don't have many rules, and if you’re familiar with the rules of Fight Club, you should be fine. </p>

    <p>Actually, just to be safe, here are the rules:</p>

    <ol>
      <li>You do not talk about Secret Santa Society.</li>
      <li>You DO NOT talk about Secret Santa Society. Not even with people you suspect may also be S3 members.</li>
      <li>If someone asks you directly about S3, you lie. Holiday lies are acceptable.</li>
      <li>Santas remain anonymous. You are free to investigate who your santa is after the exchange, but not before.</li>
      <li>Gifts must not exceed $25 in value.</li>
      <li>Gifts must not be gift cards. Get creative, you jerk.</li>
      <li>Gifts must not be gag gifts or generic in nature. That’s not how Santa does things.</li>
      <li>Gifts must be wrapped. Don’t be a grinch.</li>
      <li>Gifts must not be labeled with who they are from, only who they are for.</li>
    </ol>

    <p>You have until Friday, December 7th at midnight to accept this invitation, or you will not be included in the automatic secret santa match.</p>

    <p>We hope to hear from you soon. Good luck.</p>

    <p>— Josh Ferrara &amp; the S3</p>

  </body>
</html>

app/views/email_matches/remind_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @user.first_name %></h1>
    <p>This email is here to remind you that you have exactly 12 hours left to accept your invitation to join the Secret Santa Society.</p>

    <p>In case you've misplaced your invitation, here's how it works:</p>

    <ol>
      <li>If you choose to participate, visit <a href="<%= @url %>"><%= @url %></a> by the end of today — Friday, December 7th — to accept this invitation.</li>
      <li>At midnight on Friday, December 7th you will receive an email with a Secret Santa match name. This is the person you will be buying a gift for.</li>
      <li>On Saturday, December 15th the S3 will convene (that means get together for a Christmas party) for our annual gathering at an undisclosed location, and gifts will be exchanged anonymously.</li>
    </ol>

    <p>As of this email, you have exactly 12 hours remaining before your invitation will expire. Your presence will be missed if you're unable to join us.</p>

    <p>We hope to hear from you soon. Good luck.</p>

    <p>— Josh Ferrara &amp; the S3</p>

  </body>
</html>

app/views/email_matches/reminder_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @user.first_name %></h1>
    <p>This email is here to remind you that you have exactly 12 hours left to accept your invitation to join the Secret Santa Society.</p>

    <p>In case you've misplaced your invitation, here's how it works:</p>

    <ol>
      <li>If you choose to participate, visit <a href="<%= @url %>"><%= @url %></a> by the end of today — Friday, December 7th — to accept this invitation.</li>
      <li>At midnight on Friday, December 7th you will receive an email with a Secret Santa match name. This is the person you will be buying a gift for.</li>
      <li>On Saturday, December 15th the S3 will convene (that means get together for a Christmas party) for our annual gathering at an undisclosed location, and gifts will be exchanged anonymously.</li>
    </ol>

    <p>As of this email, you have exactly 12 hours remaining before your invitation will expire. Your presence will be missed if you're unable to join us.</p>

    <p>We hope to hear from you soon. Good luck.</p>

    <p>— Josh Ferrara &amp; the S3</p>

  </body>
</html>

app/views/email_matches/send_matches.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <h1>Greetings, <%= @user.first_name %></h1>
    <p>
      A secret santa match has been automatically selected for you. This year, you will be selecting a gift for:
    </p>
    <p>
      <strong><%= @user.user.first_name + " " + @user.user.last_name %></strong>
    </p>
    <p>
      Don't forget, the annual gathering of the Secret Santa Society is Saturday, December 15th at 7pm. The location is 18114 Pinehurst Drive, Prairieville, Louisiana. You have approximately one week to find the perfect gift.
    </p>
    <p>
      A main entree will be provided, but we ask that each member bring a snack or appetizer item of their choice with enough to share with 10-15 people.
    </p>
    <p>— Josh Ferrara &amp; the S3</p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secret Santa Society</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <!-- <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a> -->

        <a class="brand" href="<%= root_url %>">Secret Santa Society</a>
        <div class="nav-collapse">
          <ul class="nav">
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <div class="row">
      <div class="span12 alerts">
      </div>
    </div>

    <div class="row">
      <div class="span12 content">
        <%= yield %>
      </div>
    </div>

  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rsvp, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :rsvp, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/confirm_rsvp.js.erb
if (<%= @user.nil? %>){

  $('div.alerts').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>×</button><h4>Not so fast</h4>We don't have an outstanding invitation for that email address. Please use the email address where you recieved your invitation.</div>")
} else if (<%= !@user.nil? %>){
  $('div.content').slideUp(200, 'swing');
  $('div.alerts').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>×</button><h4>Greetings, <%= @user.first_name unless @user.nil? %></h4>You are now a member of the S3. Keep an eye on your email inbox for more instructions.</div>");

}

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <span class="badge badge-success"><%= User.where(rsvp: true).count %></span>
  <span class="badge badge-important"><%= User.where(rsvp: false).count %></span>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

<%= link_to "Invite Santas", invite_users_path, confirm: "Are you sure you want to invite all users?", class: "btn" %>

<%= link_to "Remind Santas", remind_users_path, confirm: "This will email all users who haven't RSVP'd.", class: "btn" %>

<%= link_to "Match Santas", match_path, class: "btn" %>

<%= link_to "Email Matches", send_matches_path, confirm: "Are you sure you want to email all matches?", class: "btn" %>


<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Name</th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:receiver_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><i class="icon-<%= user.rsvp ? "ok" : "remove" %>"></i></td>
        <td><%= user.first_name + " " + user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.user.first_name + " " + user.user.last_name if user.user %></td>
        <td>
          <%= link_to invite_user_path(user), class: "btn" do %>
            <i class="icon-envelope"></i>
          <% end %>
          <%= link_to edit_user_path(user), class: "btn" do %>
            <i class="icon-pencil"></i>
          <% end %>
          <%= link_to user_path(user), method: :delete, confirm: "Are you sure you want to delete " + user.first_name + "?", class: "btn btn-danger" do %>
            <i class="icon-trash"></i>
          <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/rsvp.html.erb
<p>Welcome to the Secret Santa Society. You're about to join an elite group of gift givers that common Christmas lovers can only dream about being a part of.</p>

<p>Enter your email address below to accept your invitation and begin your membership in the S3. And remember, we DO NOT talk about S3.</p>

<%= form_tag(confirm_rsvp_path, method: 'get', remote: true) do %>
  <div class="control-group">
    <div class="controls">
      <%= text_field_tag 'email', nil, placeholder: 'Your email address', :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= submit_tag 'Confirm Invitation', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @user.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rsvp) %>:</strong></dt>
  <dd><%= @user.rsvp %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>